### ISSUE TITLE
Unit tests fail on main branch after merging visualisation script branch

### ISSUE THREAD

**Issue by AnejSvete** [BoevaLab/latte#17]
After merging #10, the unit tests suddenly fail on the main branch (even though the branch did not have any new unit tests). 
It seems to be a known issue: https://github.com/protocolbuffers/protobuf/issues/10051. @pawel-czyz, what do you think we should do?

**Comment by pawel-czyz** [comment]
You're right, the last release of `protobuf` broke CanSig's pipeline as well. Florian pinned the version to `protobuf~=3.19.0` and it worked. I think we can do this here. I hope #18 will fix it.
